# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deadlock_trace.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deadlock_trace.proto',
  package='seastar.deadlock_detection',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x65\x61\x64lock_trace.proto\x12\x1aseastar.deadlock_detection\"\x9c\x04\n\x0e\x64\x65\x61\x64lock_trace\x12\x43\n\x04type\x18\x01 \x02(\x0e\x32\x35.seastar.deadlock_detection.deadlock_trace.event_type\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\r\n\x05value\x18\x03 \x01(\x04\x12H\n\x06vertex\x18\x04 \x01(\x0b\x32\x38.seastar.deadlock_detection.deadlock_trace.typed_address\x12\x45\n\x03pre\x18\x05 \x01(\x0b\x32\x38.seastar.deadlock_detection.deadlock_trace.typed_address\x12\x0b\n\x03sem\x18\x06 \x01(\x04\x12\r\n\x05\x65xtra\x18\x07 \x01(\t\x1a\x31\n\rtyped_address\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\x04\x12\x0f\n\x07type_id\x18\x02 \x01(\x04\"\xc2\x01\n\nevent_type\x12\x08\n\x04\x45\x44GE\x10\x00\x12\x0f\n\x0bVERTEX_CTOR\x10\x01\x12\x0f\n\x0bVERTEX_DTOR\x10\x02\x12\x0f\n\x0bVERTEX_MOVE\x10\x03\x12\x0c\n\x08SEM_CTOR\x10\x04\x12\x0c\n\x08SEM_DTOR\x10\x05\x12\x0c\n\x08SEM_MOVE\x10\x06\x12\r\n\tSTRING_ID\x10\x07\x12\r\n\tFUNC_TYPE\x10\x08\x12\x0e\n\nSEM_SIGNAL\x10\t\x12\x0c\n\x08SEM_WAIT\x10\n\x12\x11\n\rSEM_WAIT_CMPL\x10\x0b'
)



_DEADLOCK_TRACE_EVENT_TYPE = _descriptor.EnumDescriptor(
  name='event_type',
  full_name='seastar.deadlock_detection.deadlock_trace.event_type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EDGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERTEX_CTOR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERTEX_DTOR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERTEX_MOVE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_CTOR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_DTOR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_MOVE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STRING_ID', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FUNC_TYPE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_SIGNAL', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_WAIT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEM_WAIT_CMPL', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=399,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_DEADLOCK_TRACE_EVENT_TYPE)


_DEADLOCK_TRACE_TYPED_ADDRESS = _descriptor.Descriptor(
  name='typed_address',
  full_name='seastar.deadlock_detection.deadlock_trace.typed_address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='seastar.deadlock_detection.deadlock_trace.typed_address.address', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='seastar.deadlock_detection.deadlock_trace.typed_address.type_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=396,
)

_DEADLOCK_TRACE = _descriptor.Descriptor(
  name='deadlock_trace',
  full_name='seastar.deadlock_detection.deadlock_trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='seastar.deadlock_detection.deadlock_trace.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='seastar.deadlock_detection.deadlock_trace.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='seastar.deadlock_detection.deadlock_trace.value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vertex', full_name='seastar.deadlock_detection.deadlock_trace.vertex', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre', full_name='seastar.deadlock_detection.deadlock_trace.pre', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sem', full_name='seastar.deadlock_detection.deadlock_trace.sem', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra', full_name='seastar.deadlock_detection.deadlock_trace.extra', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEADLOCK_TRACE_TYPED_ADDRESS, ],
  enum_types=[
    _DEADLOCK_TRACE_EVENT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=593,
)

_DEADLOCK_TRACE_TYPED_ADDRESS.containing_type = _DEADLOCK_TRACE
_DEADLOCK_TRACE.fields_by_name['type'].enum_type = _DEADLOCK_TRACE_EVENT_TYPE
_DEADLOCK_TRACE.fields_by_name['vertex'].message_type = _DEADLOCK_TRACE_TYPED_ADDRESS
_DEADLOCK_TRACE.fields_by_name['pre'].message_type = _DEADLOCK_TRACE_TYPED_ADDRESS
_DEADLOCK_TRACE_EVENT_TYPE.containing_type = _DEADLOCK_TRACE
DESCRIPTOR.message_types_by_name['deadlock_trace'] = _DEADLOCK_TRACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

deadlock_trace = _reflection.GeneratedProtocolMessageType('deadlock_trace', (_message.Message,), {

  'typed_address' : _reflection.GeneratedProtocolMessageType('typed_address', (_message.Message,), {
    'DESCRIPTOR' : _DEADLOCK_TRACE_TYPED_ADDRESS,
    '__module__' : 'deadlock_trace_pb2'
    # @@protoc_insertion_point(class_scope:seastar.deadlock_detection.deadlock_trace.typed_address)
    })
  ,
  'DESCRIPTOR' : _DEADLOCK_TRACE,
  '__module__' : 'deadlock_trace_pb2'
  # @@protoc_insertion_point(class_scope:seastar.deadlock_detection.deadlock_trace)
  })
_sym_db.RegisterMessage(deadlock_trace)
_sym_db.RegisterMessage(deadlock_trace.typed_address)


# @@protoc_insertion_point(module_scope)
